version: '3'
services:
  product-service:
    build: ./product_service
    ports:
      - "8001:8001"
    env_file:
      - ./product_service/.env
    networks:
      - app-network

  user-service:
    build: ./user_service
    ports:
      - "8002:8002"
    env_file:
      - ./user_service/.env
    networks:
      - app-network

  order-service:
    build: ./order_service
    ports:
      - "8003:8003"
    env_file:
      - ./order_service/.env
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - product-service
      - user-service
      - order-service
    networks:
      - app-network

networks:
  app-network:
